import Head from 'next/head'
import React from 'react'

const HeadComponent = () => {
  return (
    <Head>
        <title>Dignity International Agency</title>
        <meta name="Dignity Agency Worker Saudi Malaysia Oman" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadComponent