import { Link } from '@chakra-ui/react'
import Head from 'next/head'
import React from 'react'
import DrawerComponent from './DrawerComponent'
import styles from './HeadComponent.module.css'

const HeadComponent = () => {
  return (
    <div>
        <Head>
            <title>Dignity International Agency</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.png" />
        </Head>
        <nav className={styles.nav}>
            <Link href='/'>
            <div className={styles.navl}>
                <img src="logo.png" alt ="logodignity"/>
                <div className={styles.h3dig}>
                    <h3>DIGNITY</h3>
                    <h4>INTERNATIONAL AGENCY</h4>
                </div>
            </div>
            </Link>
      
            <div className={styles.navr}>
                <Link href='/'>
                    <h4>HOME</h4>
                </Link>
                <Link href='about'>
                    <h4>ABOUT US</h4>
                </Link>
                <Link href='whyhireus'>
                    <h4>WHY HIRE US</h4>
                </Link>
                <Link href='whyhireus'>
                    <h4>NOTICE</h4>
                </Link>
              <DrawerComponent/>
            </div>
        </nav>  
    </div>
  )
}

export default HeadComponent